Pop up window and card element to Array
Yacoubou-seidou/Portfolio pull request #12
Opened 2023-03-07 15:17 UTC by Yacoubou-seidou

### Pop up window and card element to Array
- Add array with all projects details in javascript
- Store all minimum required data for a project in the array
- Add a modal with the correct project detail
- Close the modal when clicking on the close button
- Project section is created dynamically using the information stored in that JavaScript
- Add a modal pop-up when checking project details on mobile
- Add a modal pop-up when checking project details on desktop
- Template 1 design

2023-03-07 15:35 UTC, Ghiftee requested changes
## STATUS: CHANGES REQUIRED ♻️♻️
Hello @Yacoubou-seidou  and @Ferizad 👋🏽 

Good job working on the project so far! 
To highlight 👍🏽 
✔️ App runs as expected
✔️ Linters are set up correctly
✔️ README is professional

However, there are some issues that you need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMDk5MjcyOTYyNDJkZjE3ZjNhNzc0MzA1NTE4YzRjYzZhYmFmOTQwMCZjdD1n/W5ZUxqXT1lmiysXsDE/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._
- [ ] As your design should look exactly like the figma design, kindly correct the spacings in the images below:

### Your design
![Screenshot 2023-03-07 at 16 28 24 (2)](https://user-images.githubusercontent.com/64774936/223469742-a03d1ad5-53fc-48fb-a505-053df423d976.png)

### Figma design
![Screenshot 2023-03-07 at 16 28 18 (2)](https://user-images.githubusercontent.com/64774936/223469846-c714632d-d409-4372-8a3d-22eef4435bfe.png)

### Your design
![Screenshot 2023-03-07 at 16 34 12 (2)](https://user-images.githubusercontent.com/64774936/223470168-ef9a9bde-36e2-473c-b2f0-f4ba05365b10.png)

### Figma design
![Screenshot 2023-03-07 at 16 29 15 (2)](https://user-images.githubusercontent.com/64774936/223470257-3c5ec112-76cf-4438-8a69-5e5cd287301b.png)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-03-07 15:35 UTC, Ghiftee commented on index.html
> +            <h2 tabindex="0">Tonic</h2>
- [ ] Kindly remove the commented code from your project has it helps you have a cleaner codebase

2023-03-07 17:00 UTC, tufoinnkuo10 requested changes
Hi @team

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ design well followed

Required Changes ♻️
Check the comments under the review
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2023-03-07 17:00 UTC, tufoinnkuo10 commented on style.css
> +
- [optional] kinldy make the button details hover on line 304 to have the color `#6070FF`.

2023-03-07 17:00 UTC, tufoinnkuo10 commented on script.js
> +    livelink: 'https://yacoubou-seidou.github.io/Portfolio/',
- [ ] please, like the previous reviewer noted, kindly ensure your` see live` and `seesource` buttons follow the Figma design. Please reduce the gap between them for both the mobile and desktop version
- [optional] you can as well reduce your mobile popup height, so everything can be seen without scrolling 
Yours            
![Screenshot (872)_LI](https://user-images.githubusercontent.com/65298048/223493117-10e7f020-1799-43f5-a100-635295d36f22.jpg)  
figma
  ![Screenshot (873)](https://user-images.githubusercontent.com/65298048/223493347-1bcf0eb0-a9fb-4ace-a67d-705be040859b.png)

2023-03-08 05:06 UTC, Nemwel-Boniface reviewed
## Hello @Yacoubou-seidou   👋,

I am Nemwel your reviewer.


## _This is an additional review as a result of the second opinion request._

I have inspected your project and the design of the buttons looks good enough. Students are required to replicate the Figma designs but it is not always a strict requirement that it looks exactly as the Figma design looks it only has to be similar adhering to the Fonts, colors, images and typography that is provided. We understand that learning to style your projects is a process and you have done well and keep improving on your CSS skills. :fire: 

As this was the only reason that your project was not approved please go ahead and request another  review in your dashboard and the next reviewer will approve it immediately :rocket: 


In case anything is not 100% clear tag me @Nemwel-Boniface so that I get the notification.

Keep rocking 🚀!

2023-03-08 06:39 UTC, binhussen approved these changes
Hi @Yacoubou-seidou , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-08 06:41 UTC, merged